# Generated by Django 3.2.9 on 2021-11-03 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_de_creation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 10, 3, 45, 143341, tzinfo=utc)),
        ),
    ]
